name: unify
description: A sample command-line application.
version: 3.0.0
homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0
  analyzer: '<4.2.0'
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.19.4
