name: unify_flutter
description:  An efficient, flexible Flutter-Native hybrid communication framework for seamless module integration and automatic code generation. 
version: 3.0.1
homepage: https://github.com/didi/Unify

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  args: ^2.3.0
  analyzer: '>=4.1.0 <4.2.0'
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.19.4
